replicaCount: 3

image:
  repository: denisber1984/mypolybot
  tag: "polybot-image-v1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer  # Use LoadBalancer for AWS
  port: 8443

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: my-python-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
namespace: den-pollyapp  # Set namespace to den-pollyapp
