version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 023196572641.dkr.ecr.us-east-2.amazonaws.com

  pre_build:
    commands:
      - echo Building the Docker image...
      - docker build -t mypolybot .
      - docker tag mypolybot:latest 023196572641.dkr.ecr.us-east-2.amazonaws.com/denber1984/app-repo:latest

  build:
    commands:
      - echo Pushing the Docker image...
      - docker push 023196572641.dkr.ecr.us-east-2.amazonaws.com/denber1984/app-repo:latest

  post_build:
    commands:
      - echo Deploying to EKS...
      - aws eks update-kubeconfig --region us-east-2 --name eks-X10-prod-01
      - kubectl set image deployment/my-polybot-app my-polybot-app=023196572641.dkr.ecr.us-east-2.amazonaws.com/denber1984/app-repo:latest -n den-pollyapp

artifacts:
  files:
    - buildspec.yaml
