version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    KUBECONFIG: "/root/.kube/config"

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 023196572641.dkr.ecr.us-east-2.amazonaws.com

  pre_build:
    commands:
      - echo Building the Docker image...
      - docker build -t mypolybot polybot/
      - docker tag mypolybot:latest 023196572641.dkr.ecr.us-east-2.amazonaws.com/denber1984/app-repo:latest

  build:
    commands:
      - echo Pushing the Docker image...
      - docker push 023196572641.dkr.ecr.us-east-2.amazonaws.com/denber1984/app-repo:latest

  post_build:
    commands:
      - echo Deploying to EKS...
      - aws eks update-kubeconfig --region us-east-2 --name eks-X10-prod-01
      - echo Checking IAM identity...
      - aws sts get-caller-identity
      - echo Setting image on EKS deployment...
      - kubectl set image deployment/my-polybot-app my-polybot-app=023196572641.dkr.ecr.us-east-2.amazonaws.com/denber1984/app-repo:latest -n den-pollyapp

artifacts:
  files:
    - buildspec.yaml
