apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: {{ .Release.Namespace }}
  labels:
    app: load-generator
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do wget -q -O- http://nginx-service.{{ .Release.Namespace }}.svc.cluster.local; done']
