apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: demoapp
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx</title>
    </head>
    <body>
        <h1>Welcome to Nginx</h1>
    </body>
    </html>
