apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: denisber1984/web-image:latest
        ports:
        - containerPort: 8444
        volumeMounts:
        - name: static-content
          mountPath: /usr/share/nginx/html
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: static-content
        configMap:
          name: nginx-config
