apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-den
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-custom-storageclass  # Unique StorageClass
  awsElasticBlockStore:
    volumeID: vol-05eba65191aec948e
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-2a  # Use your actual zone
