apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-jenkins-pvc
  namespace: den-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2
