apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: den-pollyapp
  name: deployment-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: den-pollyapp
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: den-pollyapp
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
