apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demoapp
  name: jenkins-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
